### ISSUE TITLE
LSF via sourcing .lsf files?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#100]
Hi,

If IT says to enable LSF a user must source an .lsf file then how will this integrate with Origen overall?  I would like to see up the LSF configuration in the site config file so all users can have it work with their app right out of the box.

thx

For csh or tcsh:
~~~shell
source /nfs/tools/lsf/conf/cshrc.lsf
~~~
For sh, ksh, or bash:
~~~shell
source /nfs/tools/lsf/conf/profile.lsf
~~~

**Comment by ginty** [comment]
Seems like the user should just source that file in the .tcshrc/.bashrc, doesn't seem like any particular integration with Origen should be required.

**Comment by info-rchitect** [comment]
ahh right, origen isn't a user, just a process.

**Comment by ginty** [comment]
Let us know how it goes with the LSF, it did work in NXP without any modifications vs. what we ran in Freescale, so I think it is pretty generic.
You might need to tweak some of the settings though, you can do that in your app config for now like this:

~~~ruby
config.lsf.resource = 'rhel6'
config.lsf.queue = 'shortq'
~~~

We do still have this PR open to make this more customizable at the site/company level: https://github.com/Origen-SDK/origen/pull/89
