### ISSUE TITLE
Method for including proprietary or one-off classes into SubBlocks

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#107]
A good example would be e-fuses that get imported from Excel and are used as a standard look-up table like class with some limited, and possibly proprietary, attributes and methods.  I would like to be able to assign fuses to various SubBlocks so I can access them just like register, specs, etc.

~~~ruby
$dut.fuses.myfuses
~~~

This isn't about fuses but rather the ability in Origen to add user-defined classes into the SubBlock instances.

thx

**Comment by welguisz** [comment]
@info-rchitect ... have you looked at 'monkey-patching' in Ruby.  This way you can create proprietary things in a block or code.

**Comment by coreyeng** [comment]
I've done something similar for the SIM block in some of our devices. I just created a sub block in the top-level application then imported it later in the same file. For example, in my top level, I have:

~~~
class Sim
      include Origen::Model
      include RosettaStone
      
      def initialize(options={})        
        add_reg :sim1,   $dut.sim_reg_base + 0x8,  32, data: { pos: 0, bits: 32 }
        add_reg :sim2,    $dut.sim_reg_base + 0x24, 32, data: { pos: 0, bits: 32 }
        add_reg :sim3,    $dut.sim_reg_base + 0x28, 32, data: { pos: 0, bits: 32 }
        ...
      end
      
      # Return a list of the 'sim_cfg' regs
      def cfg_regs(options={})
            [:sim1, :sim3]
      end
end
~~~

Then later in that file:

~~~
sub_block :sim, class_name: 'DEVICE_RGEN::Sim', base_address: sim_reg_base
~~~

Could fuses work in a similar way? Just call it <code>fuses</code> instead of <code>sim</code>?

You could also try using a mix-in (I think that's what its called) where if your fuses are defined in a separate plugin, you can set it up in such a way that 'include fuses' will provide the 'fuses' method on the top level, like how the old ARM Debug driver worked.

**Comment by ginty** [comment]
If you want rich behavior, then defining your own sub-block class is the way to go as described by @coreyeng.

The generic sub-block class though does allow you to set any attribute you like without having to define it upfront, so you could do:

~~~ruby
dut.fuses.myfuses = MyFuses.new
~~~

I'm not sure if this form works or not, if it doesn't and it works better for you we could add it:

~~~ruby
sub_block :fuses, myfuses: MyFuses.new
~~~

**Comment by info-rchitect** [comment]
Thanks everyone for the suggestions, I am going through them now, trying to figure out the best (read less brittle) way to implement.  Right now, I just have a 2-D hash called fuses that sits at the top level with the IP instance (SubBlock) name being the first key and the fuse field name being the second one.

~~~ruby
# Top Level
module PPEKit
  class Product
    include Fuses

    def initialize
      nick, options = {})
      options = {
        rev: :a0
      }.update(options)
      @nick = nick
      @revision = options[:rev]
      fail unless product_valid?
      load_product_config
      if Origen.app.import
        @import = Origen.app.import
      end
      @top_origen_path = Pathname.new("#{vendor_path.to_s}/top_level.rb")
      # Import or instantiate registers
      if @import || !@top_origen_path.exist?
        Origen.log.info("PPEKit: Importing registers and pins from #{xml_path}")
        import_from_xml("#{xml_path}")
      else
        Origen.log.info("PPEKit: Instantiating registers from Origen source...")
        require @top_origen_path.to_s.chomp(".rb")
        extend SubBlocks
        instantiate_sub_blocks()
        Origen.log.info("PPEKit: Importing pins from #{sgxml_path}")
        import_xml("#{xml_path}", pins_only: true)
      end
      import_fuses
      Origen.log.info("PPEKit: #{@name} #{@revision} model accessible as \'$dut\'")
    end

# Fuse Module
require_relative 'fuses/fuse_field'
module PPEKit
  module Fuses
  
   def fuses
     @fuses ||= Hash.new { |h,k| h[k] = {} }
   end

  def fuse_field(name, instance_name, start_addr, size, options = {})
    fuses[instance_name][name] = FuseField.new(name, start_addr, size, options)
  end

  def import_fuses
    # iterating through Excel file with roo gem
    # TODO: The following code requires fuses to be integrated with Origen core, until then just store as 2-D hash
     # ip_name = fuse_field_data.delete[:ip].symbolize
     # if self.respond_to?(instance_name)
     #   Origen.log.info("PPEKit: IP instance '#{instance_name}' already exists")
     # else
     #   Origen.log.info("PPEKit: Modeling IP instance '#{instance_name}'")
     #   sub_block instance_name, base: 0, ip_name: ip_name
     # end
     # sub_block_obj = self.send(instance_name)
     # sub_block_obj.fuse_field fuse_field_name, instance_name, fuse_field_start_addr, fuse_field_size, fuse_field_data
     fuse_field(fuse_field_name, instance_name, fuse_field_start_addr, fuse_field_size, fuse_field_data)
  end
