### ISSUE TITLE
Instantiating SubBlocks called 'GC' is a no-no

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#112]
While importing IP and registers I ran into a case where a specific class named 'GC' was causing an error during loading of the file:

~~~shell
[1] pry(#<PPEKit::Product>)>
Any class which is to be instantiated as a sub_block must include Origen::Model,
add this to GC:

  include Origen::Model


COMPLETE CALL STACK
-------------------
Sub block does not include Origen::Model!
~~~

~~~ruby
module PPEKit
  class Product
    class GC # rubocop:disable ClassLength
      include Origen::Model
~~~

This is because [GC is a reserved module referring to the Garbage Collector](https://ruby-doc.org/core-2.2.0/GC.html).  My question is whether we should put the responsibility on the app builder or on the sub_block method to check for reserved Ruby modules/classes?

thx

**Comment by ginty** [comment]
I think having Origen raise a meaningful error in this known corner case (which I guess was not easy to debug) would be a good addition.

**Comment by info-rchitect** [comment]
will do, thx
