### ISSUE TITLE
rubocop is replacing 'has_key?' with 'key?' which breaks the session store method

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#113]
The Origen session store has two methods named 'has_key?' that are getting renamed 'key?'when running rubocop via 'origen lint'.   The rubocop config option is 'Style/DeprecatedHashMethods'.

Question:  Should we do this on a per-file basis or globally?

**Comment by ginty** [comment]
Is this not an indication that these methods should really have been called key?

**Comment by info-rchitect** [comment]
well not really IMO, [Matz has said](https://github.com/bbatsov/rubocop/issues/3224) has_key? is never going away.  Do you have an answer on the question?

**Comment by ginty** [comment]
We should not be changing the lint rules over this, no.

**Comment by info-rchitect** [comment]
OK
