### ISSUE TITLE
ChipMode attributes flexible enough?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#116]
Hi,

After reviewing the ChipMode class it is obvious that the attributes fit a specific product type and don't work universally.  Ideally, an API like this might work:

~~~ruby
$dut.add_mode :native do
  number_of_cores 16
  core_freq 1800.Mhz
  L2_freq 900.Mhz
  threads 32
end
$dut.modes(:native).threads # => 32
~~~

I see that the ChipMode init handles a block but don't think it will allow anonymous attributes, will it?

thx

**Comment by ginty** [comment]
I think the mode is little more than a name right now, no problem if you want to add more richness to it.

Extending `add_mode` to optionally accept a block for richer definition seems fine, though this variation on the above API would be more Origen-native looking:

~~~ruby
$dut.add_mode :native do |mode|
  mode.number_of_cores = 16
  mode.core_freq = 1800.Mhz
  mode.L2_freq = 900.Mhz
  mode.threads = 32
end
$dut.modes(:native).threads # => 32
~~~

**Comment by info-rchitect** [comment]
OK good to hear, I needed a coding project for the weekend :)

**Comment by info-rchitect** [comment]
addressed in this [PR](https://github.com/Origen-SDK/origen/pull/136)
