### ISSUE TITLE
Origen::Parameters having scope issues

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#123]
Hi,

I have my main product class defined as such;

~~~ruby
module PPEKit
  class Product
    include Origen::TopLevel
~~~

I have some product specific parameters defined dynamically as such:

~~~ruby
module PPEKit
  class Product
    
    # CPU_MBIST_HR
    define_params :default do |params|
~~~

When I attempt to require the params file I get the following error, like it does not scope Origen::Parameters correctly, though it [should](http://origen-sdk.org/origen/guides/models/parameters/#Including_the_Parameters_API).

~~~ruby
[1] pry(#<PPEKit::Product>)> path
=> #<Pathname:./vendor/mycompany/myprod/a0/params/myprod_a0_params.rb>
[2] pry(#<PPEKit::Product>)> path.exist?
=> true
[3] pry(#<PPEKit::Product>)> require path.to_s.chomp('.rb')
NoMethodError: undefined method `define_params' for PPEKit::Product:Class
Did you mean?  define_method
[4] pry(#<PPEKit::Product>)> self.is_top_level?
=> true
~~~

Any ideas?

**Comment by ginty** [comment]
The problem here is that define_params is an instance method and not a class method.
Typically, you would call define_params within initialize.

It's possible that the docs should be updated to make this clearer.

**Comment by ginty** [comment]
Note also that in your 2nd example you would need to include `Origen::Model` or `Origen::Parameters` to make the define_params API available.

**Comment by info-rchitect** [comment]
OK yeah I figured this was my Ruby knowledge gone awry. thx
