### ISSUE TITLE
Clock model useful to folks here?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#125]
Hi,

I have been working on modeling how the whole chip operates using modes and parameters.  One model item that always get changed, when a mode is set, is the clock network.  I know Origen understands clocks when a pin is acting as a clock but I don't think it has a true clock model.  Anyway, I wrote a quick and dirty class to store my clock network and it handles the basic concept of setting a clock and checking if the clock set point is valid (within the clock range if variable and equal to the target freq if fixed).

~~~ruby
      clock :clk0 do
        users             :user1
        freq_target    100.Ghz
        freq_range    50.Ghz..125.Ghz
        clock_meta1 true
        clock_meta2  :optional
      end
      clock :clk1 do
        users              [:user2, :user3, :user4]
        freq_target     2.0.Khz
        freq_range     1.khz..2.5.Khz
        clock_meta1   false
        clock_meta2   :required
      end
~~~

Clocks are unique, I believe, because they sometimes have many owners or users.  Yes they may be instantiated at the $dut but when their set point is changed, only some IP care or are affected.  How could a clock model be integrated/extended into a $dut model that 'checks' whether tester patterns are setting the device clocks correctly.  Second, should I make a PR to upload this model as-is?  Currently, it just serves to store information I get from an Excel file, so its uses are really more for documentation creation and setting characterization search ranges.

**Comment by ginty** [comment]
I would certainly like to get a better and more cohesive solution for clocks, though I don't have a lot of experience/knowledge in this area.

Right now, I think we have a few moving parts which can be used to work with clocks within a pattern:

* The ability to create free-running clocks in patterns: http://origen-sdk.org/origen/guides/models/pins/#Pin_Clock_Functionality
* The ability to define timing waveforms to create a clock: http://origen-sdk.org/origen/guides/pattern/timing/#Complex_Timing

Additionally, I would like to introduce a patgen callback API which would make it easier to create complex vector-driven clocks, something like this:

~~~ruby
# Initialize the clk to drive 0
pin(:clk).drive(0)

# The code contained within do…end would be called every 31 cycles
tester.register_callback every_cycles: 31 do
  pin(:clk).drive(1)  # Set the clk pin to 1 on the next cycle
end

# This would get called every 32 cycles
tester.register_callback every_cycles: 32 do
  pin(:clk).drive(0)  # Drive the clk low on the next cycle
end
~~~

Having a central clock model as a place to start tying that altogether seems like a good idea, so I think we should add your existing clock model as a starting point.
Potentially if we have two definitions - the clock as defined by your API, and the pattern timing - then it would be good to evolve the clock model to fully understand those two pieces and have it automatically manipulate the vector state of the corresponding clock pins to generate the clock as it is defined.

Does the sound reasonable?

Thoughts @rlaj, @chrisnappi, @pderouen?

One request I would like to make is a slight change to the API as you show it. I know the style of block definition as you have it is quite popular in other Ruby libraries, but I prefer the more explicit style like this:

    clock :clk1 do |clk|
      clk.users = [:user2, :user3, :user4]
      clk.freq_target = 2.0.Khz
      clk.freq_range = 1.khz..2.5.Khz
      clk.clock_meta = false
      clk.clock_meta2 = :required
    end

Doing it that way would be more consistent with the existing Origen APIs to define registers, parameters, etc.

**Comment by info-rchitect** [comment]
Thanks Ginty for the detailed explanation.  You can use either form:

~~~ruby
clock :clk1 do |clk|
  clk.users = [:user2, :user3, :user4]
  clk.freq_target = 2.0.Khz
  clk.freq_range = 1.khz..2.5.Khz
  clk.clock_meta = false
  clk.clock_meta2 = :required
end
~~~

clock :clk1 do
  users = [:user2, :user3, :user4]
  freq_target = 2.0.Khz
  freq_range = 1.khz..2.5.Khz
  clock_meta = false
  clock_meta2 = :required
end

**Comment by info-rchitect** [comment]
OK the PR is nearly ready, but I have one question.  Clocks have many 'users' or IP.  Depending on how the DUT model is constructed, the IP could be defined by hand, imported, or defined automatically during clock instantiation.  I.E. If the clock has 3 IP/users and they don't exist currently, then create the sub_blocks with an attribute called 'clocks' that is an array of clock IDs that service the user/IP.  Thoughts?

@ginty @arkohler @rlaj @redxeth

**Comment by ginty** [comment]
Is 'users' common terminology in this area? Would 'ips' or even 'consumers' not be a bit clearer?

Or should we just go with 'sub_blocks' to align with general Origen terminology?

With the caveat that I don't really know what I'm talking about in this area, this seems like it would be quite nice and is probably the kind of thing you are talking about:

~~~ruby
clock :clk1 do |clk|
  clk.sub_blocks = [:ram, :atd]
end

dut.clock(:clk1).sub_blocks    # => [<sub_block: :ram>, <sub_block: :atd>]

dut.atd.clocks   # => [<clock: :clk1>]
~~~

So the question is, if the `:atd` sub_block is not actually defined anywhere else, should `<clock>.sub_blocks` instantiate a placeholder for it?

I think my vote is that it should create a default sub_block on the fly if it hasn't otherwise been defined in the DUT model by the time `my_clock.sub_blocks` is called.

**Comment by info-rchitect** [comment]
thanks @ginty.  users is our terminology, but I think we can make aliases for all three terms.  OK I will do the auto-instantiation of the IP referenced by the clocks.

**Comment by info-rchitect** [comment]
implemented [here](https://github.com/Origen-SDK/origen/pull/144)
