### ISSUE TITLE
origen t-shirts?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#127]

**Comment by ginty** [comment]
The Ruby code reference seems a bit obscure to me, but good idea generally.

You should probably add the website url too?

@redxeth was always into the idea of T-shirts and might have some good thoughts on the matter...

**Comment by info-rchitect** [comment]
I use tap all the time, mostly on hashes but arrays and strings have been done as well.  It is a good way to provide clear scope when initializing an object, versus putting a nil or empty object prior to running the init code.

~~~ruby
        new_column_names = {}.tap do |rename_hash|
            dset.vectors.to_a.each do |col_name|
              case col_name
              when /quantity/i
                rename_hash[col_name] = col_name.to_s.gsub!('quantity', 'qty')
              when /count/i
                rename_hash[col_name] = col_name.to_s.gsub!('count', 'cnt')
              when /yiel/i
                rename_hash[col_name] = col_name.to_s.gsub!('stage_set_yield', 'yld')
              when /stage_set_description/
                rename_hash[col_name] = col_name.to_s.gsub!('stage_set_description', 'oper')
              when /product_sub_family/
                rename_hash[col_name] = col_name.to_s.gsub!('product_sub_family', 'prod')
              else
                rename_hash[col_name] = col_name
              end
              rename_hash[col_name] = rename_hash[col_name].to_sym if rename_hash[col_name].is_a?(String)
            end
          end
~~~

Anyway, i thought we could write this on the back of the shirts (along with the website).

![image](https://user-images.githubusercontent.com/26782653/30003395-cedaf1e6-9081-11e7-9731-23d1c00374d9.png)

maybe too risque, thoughts?

**Comment by ginty** [comment]
Honestly that reference is a bit lost on me, potentially it seems a bit too unprofessional to me.

I like the idea of sounding a bit edgy, we should be positioning ourselves as challengers to the Status Quo, but at the same time I think it is important to appear unprofessional lest we might not be taken seriously.
That's a fine line to walk, but to me (even though I don't quite know what it means!) this seems to be crossing the line too much.

I like the font though, and the idea of having the website on the back.

**Comment by info-rchitect** [comment]
OK sounds good.  the font doesn't work well with lower cased website URL.  I actually think just reusing the Consolas font from the front (used in the code) looks nice on the back.  i will make one have a picture of it posted.  Can you send me the highest resolution version of the logo you have?
