### ISSUE TITLE
Latest build fails 'origen i'

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#128]
Hi,

Here is what I got when I tried 'origen i' on the latest build, 1:23PM CST, 9-1-17:

~~~shell
peologin02:origen $ origen i
[INFO]       0.018[0.018]    || *******************************************************************************
[INFO]       0.019[0.000]    || The following remotes need to be updated, this will now happen automatically:
[INFO]       0.019[0.000]    ||   origen_app_generators - 1.1.0
[INFO]       0.019[0.000]    ||

COMPLETE CALL STACK
-------------------
Requested local repository /users/user/origen/.origen_remotes_DO_NOT_HAND_MODIFY/origen_app_generators is within existing local repository /users/user/origen
/users/user/origen/origen/lib/origen/revision_control/git.rb:255:in `initialized?'
/users/user/origen/origen/lib/origen/revision_control/git.rb:329:in `initialize_local_dir'
/users/user/origen/origen/lib/origen/revision_control/base.rb:30:in `initialize'
/users/user/origen/origen/lib/origen/revision_control.rb:38:in `new'
/users/user/origen/origen/lib/origen/revision_control.rb:38:in `new'
/users/user/origen/origen/lib/origen/remote_manager.rb:303:in `block in update!'
/users/user/origen/origen/lib/origen/remote_manager.rb:279:in `each'
/users/user/origen/origen/lib/origen/remote_manager.rb:279:in `update!'
/users/user/origen/origen/lib/origen/remote_manager.rb:32:in `require!'
/users/user/origen/origen/lib/origen.rb:475:in `load_application'
/users/user/origen/origen/lib/origen.rb:142:in `app'
/users/user/origen/origen/lib/origen.rb:718:in `lsf'
/users/user/origen/origen/lib/origen/commands.rb:93:in `<top (required)>'
/users/user/origen/origen/bin/origen:172:in `require'
/users/user/origen/origen/bin/origen:172:in `<top (required)>'
/users/user/origen/origen/lbin/origen:17:in `load'
/users/user/origen/origen/lbin/origen:17:in `<main>'
~~~

**Comment by ginty** [comment]
Hmmm, that's weird, you're running on Linux here right?

Some how the remotes directory on your system is resolving to `/users/user/origen/.origen...` when it should be `/users/user/.origen...`.

This is the method which is generating that path: https://github.com/Origen-SDK/origen/blob/master/lib/origen/application/workspace_manager.rb#L61

Would you mind digging in to see if you can identify what the problem is? It works fine on all of our systems, so not easy to reproduce.

**Comment by info-rchitect** [comment]
OK will do, shouldn't be too hard to diagnose.  thx

**Comment by info-rchitect** [comment]
OK so here is what I found out:

- If I move the origen directory from /users/user/origen to my home directory the error goes away
- There is an options[:allow_local_adjustment] that is nil which is causing the fail. 

~~~ruby
    250:     until path.root? || File.exist?("#{local}/.git")
    251:       if File.exist?("#{path}/.git")
 => 252:         binding.pry
    253:         if options[:allow_local_adjustment]
    254:           @local = path
    255:         else
    256:           fail "Requested local repository #{local} is within existing local repository #{path}"
    257:         end
    258:       else
    259:         path = path.parent
    260:       end
    261:     end
    262:     true
    263:   end
    264:   File.exist?("#{local}/.git") &&
    265:     git('remote -v', verbose: false).any? { |r| r =~ /#{remote_without_protocol_and_user}/ || r =~ /#{remote_without_protocol_and_user.t[1] pry(#<Origen::RevisionControl::Git>)> path
=> #<Pathname:/users/user/origen>
[2] pry(#<Origen::RevisionControl::Git>)> File.exist?("#{path}/.git")
=> true
[3] pry(#<Origen::RevisionControl::Git>)> options[:allow_local_adjustment]
=> nil
~~~

When I try to set a breakpoint at the exact same spot in the origen directory I moved, it never gets to the breakpoint and here is the output from 'origen i':

~~~ruby
peologin02:origen $ origen i
/home/user/origen/origen/config/version.rb:2: warning: already initialized constant Origen::MAJOR
/home/user/origen/config/version.rb:2: warning: previous definition of MAJOR was here
/home/user/origen/origen/config/version.rb:3: warning: already initialized constant Origen::MINOR
/home/user/origen/config/version.rb:3: warning: previous definition of MINOR was here
/home/user/origen/origen/config/version.rb:4: warning: already initialized constant Origen::BUGFIX
/home/user/origen/config/version.rb:4: warning: previous definition of BUGFIX was here
/home/user/origen/origen/config/version.rb:5: warning: already initialized constant Origen::DEV
/home/user/origen/config/version.rb:5: warning: previous definition of DEV was here
/home/user/origen/origen/config/version.rb:7: warning: already initialized constant Origen::VERSION
/home/user/origen/config/version.rb:7: warning: previous definition of VERSION was here
~~~

Any ideas?

**Comment by ginty** [comment]
By the time you get down to the git driver level the problem has already occurred further upsteam, it is more likely this method is returning the wrong path: https://github.com/Origen-SDK/origen/blob/master/lib/origen/application/workspace_manager.rb#L61

It must be quite an obscure problem though, I tried cloning origen into /users/user/origen and /users/user/origen/origen on my system and both worked fine.

**Comment by info-rchitect** [comment]
so I am seeing that there are 2 .origen_remotes directories:

/users/user/origen/.origen_remotes_DO_NOT_HAND_MODIFY/origen_app_generators # empty
/home/user/.origen_remotes_DO_NOT_HAND_MODIFY # has content

Here is what I see in the file you mention above:

~~~ruby
[1] pry(#<Origen::Application::WorkspaceManager>)> @remotes_directory
=> "/users/user/origen/.origen_remotes_DO_NOT_HAND_MODIFY"
[2] pry(#<Origen::Application::WorkspaceManager>)> File.exist?(@remotes_directory)
=> true
[3] pry(#<Origen::Application::WorkspaceManager>)> Dir.entries(@remotes_directory)
=> [".", "..", "origen_app_generators"]
[4] pry(#<Origen::Application::WorkspaceManager>)> gen_dir = "#{@remotes_directory}/origen_app_generators"
=> "/users/user/origen/.origen_remotes_DO_NOT_HAND_MODIFY/origen_app_generators"
[5] pry(#<Origen::Application::WorkspaceManager>)> File.exist?(gen_dir)
=> true
[6] pry(#<Origen::Application::WorkspaceManager>)> Dir.entries(gen_dir)
=> [".",~~~ ".."]
~~~

Is Origen somehow creating empty directories in a new location versus previous versions?

thx

**Comment by ginty** [comment]
Dunno tbh.

If your workspace is `/some/path/my_app`, then the remotes dir should be `/some/path/.my_app_remotes_DO_NOT_HAND_MODIFY`, i.e. it is created outside of and parallel to the application workspace it is associated with.

If you delete both of the .origen_remotes dirs, does that help?

**Comment by info-rchitect** [comment]
OK so it is due to a .git directory being parallel to the .origen_remotes.  I removed the .git directory and it worked just fine.  Bug or user issue?

**Comment by ginty** [comment]
I guess this would probably explain it:

* You used to have an Origen workspace at `/users/user/origen`
* You decided you wanted to move it to `/users/user/origen/origen`
* In the process of doing the move, the `.git` directory was left in the original location

If you think that could have occurred here, then yes, user error and a situation that we couldn't reasonably be expected to anticipate or handle.

**Comment by info-rchitect** [comment]
OK sounds good to me.
