### ISSUE TITLE
String#symbolize enhancement

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#145]
Hi,

Currently when I run symbolize on some particularly nasty CSV column names I get adjacent underscores and symbols ending with an underscore.  I currently get around this by doing the following:

~~~ruby
row.keys.map { |k| k.symbolize.to_s.include?('__') ? k.symbolize.to_s.squeeze('_').chomp('_').to_sym : k.symbolize.to_s.chomp('_').to_sym
~~~

What do folks think about elimiating adjacent underscores and removing ending underscores as default behavior?

thx

**Comment by info-rchitect** [comment]
@rlaj @chrisnappi @coreyeng @ginty any thoughts?

**Comment by rlaj** [comment]
Can't say I do much of this so not really familiar with the use case or the reason for the extra underscores, but changing the default behavior to something that's not necessarily intuitive gives me a little pause.  What if the default stayed the same, but you added the acceptance an arg.

```ruby
row.keys.map { |k| k.symbolize(:clean) }

def symbolize(arg = nil)
   # do your thing if arg == :clean
end
```

**Comment by info-rchitect** [comment]
Hi @rlaj just a little background.  it is the current behavior that is causing the double_underscores and trailing underscore.  This is due to it substituting 2 forbidden characters in a row or having one on the end of the String.  Here are some examples:

~~~ruby
[1] pry(#<PPEKit::Product>)> "Example String".symbolize
=> :example_string
[2] pry(#<PPEKit::Product>)> "Example  String".symbolize
=> :example__string
[3] pry(#<PPEKit::Product>)> "Example  String ".symbolize
=> :example__string_
~~~

Would people really ever want the last 2 symbols?  Wouldn't everyone just want all three strings to be converted to :example_string?

**Comment by rlaj** [comment]
Got it, makes sense.

**Comment by info-rchitect** [comment]
OK will add to existing PR
