### ISSUE TITLE
where are technology constants modeled?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#151]
Hi,

Throughout the semiconductor ecosystem there are technology constants like leakage maturity factor, various DIB parameters, pin electronics accuracy, etc.  Of course, if Origen modeled everything I wouldn't be asking this question and I know Origen::Parameters can store any type of data sufficiently.  But when I was working [this PR](https://github.com/Origen-SDK/origen/pull/150) I realized that having a central place to store 'unmodeled' parameters might be a good thing.  The PR currently looks to evaluate a spec formula by checking Origen::PowerDomains and Origen::Clocks nominal values.  But if there was a perhaps a reserved namespace in Origen::Parameters where these unmodeled parameters could be stored then any code could check there when evaluating a reference (identified as a Symbol).  Thoughts?

**Comment by ginty** [comment]
I'm definitely not opposed to adding in official model APIs for things like that.

Alternatively though, could you update your spec evaluator to accept a string value in single quotes? This could then reference any parameter you like and it would be eval'd at runtime similar to how you are dealing with the power and clk references:

~~~ruby
spec :memio_voh_offset, :dc do |s|
  s.symbol "Voh_offset"
  s.description = "Output high voltage with offset"
  s.max = ":vmemio * 0.8 - 'dut.params.offsets.voh'"
end
~~~
