### ISSUE TITLE
Open Sourcing an Origen::Specs schema?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#154]
For all the folks using Origen::Specs, what do you think about open-sourcing a specs schema?  I believe @welguisz has one up and running, does anyone else?  As part of the Origen::Specs rework I think making the schema part of the deliverable would be great.  Thoughts?

**Comment by ginty** [comment]
I don't think a schema definition should be under the responsibility of Origen.

Obviously you can use Origen to generate any view you like, but I don't think we should have an opinion on what an industry standard schema should be for specs or anything else.
If you feel that the industry needs a specs schema, then that should be tackled through IEEE channels and not under the Origen name.

To do otherwise would be to start positioning Origen as some kind of competing standards body and that is not really where we want to go.

**Comment by info-rchitect** [comment]
@ginty, thx

**Comment by chrisnappi** [comment]
Note sure how relevant it is to this discussion, but this STIL guide is the most succinct reference I have found.
http://grouper.ieee.org/groups/1450/dot4/docs_for_wg_meetings/stilrefguideD03.pdf

**Comment by info-rchitect** [comment]
@chrisnappi nice link, too bad the STIL definition of a spec is not nearly ready for a real world implementation.  

~~~c
Spec (SPEC_NAME) {// this block statement defines variable values for a given category( CategoryCAT_NAME{( VAR_NAME = time_expr; )*// define only the Typ value( VAR_NAME {(Mintime_expr;) (Ty ptime_expr;) (Maxtime_expr;) } )*} )+}
~~~

We need a 4-D hash to describe all specs and it only has a 1D implementation.

**Comment by chrisnappi** [comment]
I am no expert, but I believe you add dimensions via 'Environment' and 'Categories'.

**Comment by info-rchitect** [comment]
@chrisnappi I wonder if anyone has ever used STIl specs for anything...

**Comment by chrisnappi** [comment]
The Teradyne spec sheets were actually designed to be STIL compliant(the concept of environment, selectors and categories is a direct mapping).  Some testers do use it as their native file format as well.  Most traction has just been as WGL replacement though.

**Comment by chrisnappi** [comment]
Been looking at some more STIL examples.  Can you posit an example '4D' spec problem?  I would like to see how it could be expressed.

**Comment by info-rchitect** [comment]
Hi Chris, sure.  In the case below I am doing a quick and dirty mode versus actually using Origen::ChipMode as I should.  Also I am using an internal versiion of the spec API where sub_type and mode are handled via an options hash versus a straight argument.  otherwise everything is the same and should suffice for the exercise.

thx

~~~ruby
      [:vcc_3p3, :vcc_1p8].each do |mode|
        spec :vih_ac, :dc, sub_type: :my_reset_pin, mode: mode do |s|
          s.symbol = 'Vih_ac'
          s.description = 'Input High Voltage'
          s.min = '0.85 * :vdda'
          s.max = ':vcc + 0.5'
          s.unit = 'V'
        end
        spec :vil_ac, :dc, sub_type: :my_reset_pin, mode: mode do |s|
          s.symbol = 'Vil_ac'
          s.description = 'Input Low Voltage'
          s.min = -0.5
          s.max = '0.3 * :vcc'
          s.unit = 'V'
        end
      end
~~~

**Comment by chrisnappi** [comment]
Am I missing a dimension?

```
     Spec spec {
         Category vcc_3p3 {
             vdda { Min '3.0'; Typ '3.3'; Max '3.6'; }
             vcc { Min '3.0'; Typ '3.3'; Max '3.6'; }
             Vih_ac { Min '0.85 * vdda'; Max 'vcc + 0.5'; }
             Vil_ac { Min '-0.5'; Max '0.3 * vcc'; }
         }
         Category vcc_1p8 {
             vdda { Min '1.7'; Typ '1.8'; Max '1.9'; }
             vcc { Min '1.7'; Typ '1.8'; Max '1.9'; }
             Vih_ac { Min '0.85 * vdda'; Max 'vcc + 0.5'; }
             Vil_ac { Min '-0.5'; Max '0.3 * vcc'; }        
         }
     }
```

**Comment by chrisnappi** [comment]
You would then reference the spec like:

`pta_vih = standard_specs.vdd_1p8.Vih_ac.mins`

**Comment by info-rchitect** [comment]
@chrisnappi  you missed the sub_type :my_reset_pin.  In this case, i only showed a single sub-type but in practice there are many types.

**Comment by chrisnappi** [comment]
Gotcha - so yep for that in STIL you would have to use pad_type_Vih_ac/pad_type_Vil_ac - but you are going to have to render like that to ATE anyway..

**Comment by chrisnappi** [comment]
Actually I take that back.  It seems that one of the enhancements in P1450.4 was to add the concept of multiple spec tables.  Teradyne has also enhanced IG-XL (UltraFlex vairent) to support this.  

So it would be:
```
     Spec my_reset_pin {
         Category vcc_3p3 {
             vdda { Min '3.0'; Typ '3.3'; Max '3.6'; }
             vcc { Min '3.0'; Typ '3.3'; Max '3.6'; }
             Vih_ac { Min '0.85 * vdda'; Max 'vcc + 0.5'; }
             Vil_ac { Min '-0.5'; Max '0.3 * vcc'; }
         }
         Category vcc_1p8 {
             vdda { Min '1.7'; Typ '1.8'; Max '1.9'; }
             vcc { Min '1.7'; Typ '1.8'; Max '1.9'; }
             Vih_ac { Min '0.85 * vdda'; Max 'vcc + 0.5'; }
             Vil_ac { Min '-0.5'; Max '0.3 * vcc'; }        
         }
     }
    Selector mins {
             vdda Min;
             vcc Min;
             Vih_ac Min;
             Vil_ac Min;
     }
    Selector maxs {
             vdda Max;
             vcc Max;
             Vih_ac Max;
             Vil_ac Max;
     }
```

**Comment by chrisnappi** [comment]
Curious if you have contacts in Advantest knowledgeable in ST8 if you can ask if they are going to have support for Specs/Categories/Selectors..  It actually looks like both LTX and Teradyne are attempting to at least be compatible.

**Comment by info-rchitect** [comment]
@chrisnappi i will ask for sure.  This conversation leads me to believe that exporting to STIL would be advantageous right?

**Comment by chrisnappi** [comment]
Well that, and also supporting the way that STIL adds dimensions to specs, or at least making it easy to map to.

**Comment by info-rchitect** [comment]
@chrisnappi doesn't Origen map perfectly now?

**Comment by chrisnappi** [comment]
I don't know - I have never used Origen for specs :D 

This has gotten me interested though - will play with it a bit.

**Comment by info-rchitect** [comment]
@chrisnappi any chance you can take a peek at the RFC for ATE levels generator today?
