### ISSUE TITLE
Where would an ATE levels generator get placed namespace-wise?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#159]
I am going to start an ATE levels generator for the 93k.  Where should it go?  Are there any guidelines for creating such a generator that  will help make it integrate well with a multi-platform code base?

thx

**Comment by ginty** [comment]
Here are some pointers about how to go about adding a relatively simple generator (like a timing file generator) to V93K...

All the meat of the code lives in `lib/origen_testers/smartest_based_tester/base`, so make a new class in there for your generator - copy the PatternCompiler one as a starting point.

Then make another entry in `lib/origen_testers/smartest_based_tester/v93k`, again copying the PatternCompiler. All this one really does is identify the V93K-specific template that will be used. The hope is the for something like SMT8, all that will be required is to create another directory like this which references another set of templates.

All your generator really needs to do is include `include OrigenTesters::Generator`, then whatever else you add will be specific to whatever APIs you want to expose and what variables you want to clean up/process before they hit the template.

Add your template to `lib/origen_testers/smartest_based_tester/v93k/templates`, again looking at some of the existing ones for inspiration.

Instantiate your generator as shown here, https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/smartest_based_tester/base/generator.rb#L110

Any methods you wanted to expose to the interface, just define them in the generator, then the interface could call them as `timing.some_method` assuming you had instantiated the generator as `timing`.

In the case of the timing file, if you don't want to really expose anything to the interface, then make a reference to it here, just to make sure that it gets instantiated: https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/smartest_based_tester/base/generator.rb#L56
Or, maybe you want the interface to call something like `timing.enable` or something to allow the application to optionally decide whether or not to generate a timing file.

If your generator gets instantiated, then Origen will then automatically render its template at the end of the program generation run.
So just update the template to output what you want, and update the generator with the necessary business logic to support the template - e.g. in the case to extract the timing information from the DUT and process it in a way that makes the template side logic as simple as possible.

**Comment by info-rchitect** [comment]
@ginty thanks much.  any major difference for a flow generator.  a team member is going to make one for the Sapphire tester platform.

**Comment by ginty** [comment]
Flow generator is a bit different.

Probably if you are going to add support for a new tester, I would recommend adding the basic info here, e.g. name of the tester, what files you want to generate, etc.
Then I can set up a branch with a basic skeleton, then you and your team can take it from there.
