### ISSUE TITLE
Origen doc helpers 0.5.1 is broken

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#168]
All,

When doing a bundle update today, I get this error:

~~~shell
Bundler::GemspecError: Could not read gem at /home/me/.origen/gems/ruby/2.3.0/cache/origen_doc_helpers-0.5.1.gem. It may be corrupted.
An error occurred while installing origen_doc_helpers (0.5.1), and Bundler cannot continue.
Make sure that `gem install origen_doc_helpers -v '0.5.1'` succeeds before bundling.               
~~~

I noticed the plugin was updated to version 0.5.1 yesterday.  Fixing the plugin version to '0.5.0' in my Gemfile fixed the issue.

~~~ruby
  gem 'origen_doc_helpers', '0.5.0'      
~~~

**Comment by pderouen** [comment]
@info-rchitect, I've been using 0.5.1 from windows and linux.  The changes were pretty superficial.  I'm not sure how it can cause the issue you're seeing.  Did you try a 'bundle install' from your app directory?
Here's the changes:
https://github.com/Origen-SDK/origen_doc_helpers/compare/master@%7B0.5.0%7D...master

**Comment by info-rchitect** [comment]
@pderouen yes myself and another can replicate the issue and have done bundle install from the app directory (that is what caused the error).  It could be something on our side but then why would changing the version solve it?  can you try it using a fresh install and not the working area where you did your dev work?

**Comment by pderouen** [comment]
I asked somebody else to try installing our app on their PC.  No bundler complaints.  0.5.1 of doc helpers installed successfully.  I'm at a loss.  Which version of bundler are you using?

**Comment by pderouen** [comment]
@info-rchitect by the way the bug fix in 0.5.1 is only to fix the alignment of the top row of bits when generating web docs.

**Comment by rlaj** [comment]
0.5.1 installed ok for me just a few minutes ago.

**Comment by pderouen** [comment]
We've installed using bundler 1.15.3 & 1.15.0 from our end

**Comment by info-rchitect** [comment]
hmmm very weird but it is broken for everyone in our environment.  any ideas?

**Comment by info-rchitect** [comment]
@pderouen Are you installing this version of the plugin from github or are you installing from an internal gem server?

**Comment by pderouen** [comment]
We're installing it from rubygems.org.  I got a hit on google for the error message, may be something useful:
https://stackoverflow.com/questions/18689590/bundle-install-tries-to-use-cache-file

@ginty, @priyavadan, any ideas how to solve this or if there's anything that can be done from our end to prevent it?

**Comment by info-rchitect** [comment]
turned out to be that too many locks were consumed on our servers

**Comment by pderouen** [comment]
Thank you for following up on this.
