### ISSUE TITLE
Odd package setting behavior

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#169]
Hi,

If I set the top level package to a value that does not exist, it does not complain immediately.  Instead it allows it and then complains if I try to access any pins information going forward, until I reset the DUT package to nil. 

~~~shell
[1] pry(main)> dut.package = :bl5
=> :bl5
[2] pry(main)> dut.pins(:tdo).meta
RuntimeError: The package bl5 of PPEKit::Product has not been defined!
from /users/me/origen/origen/lib/origen/top_level.rb:75:in `current_package'
[3] pry(main)> dut.pins.size
RuntimeError: The package bl5 of PPEKit::Product has not been defined!
from /users/me/origen/origen/lib/origen/top_level.rb:75:in `current_package'
[4] pry(main)> dut.packages
=> []
[5] pry(main)> dut.package = nil
=> nil
[6] pry(main)> dut.pins.size
=> 775
~~~

Shouldn't this improper setting of the package be forbidden?

thx

**Comment by ginty** [comment]
Probably

**Comment by info-rchitect** [comment]
OK, I incorporated a fix into [this PR](https://github.com/Origen-SDK/origen/pull/172)
