### ISSUE TITLE
Pin metadata for various scopes

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#173]
Hi,

As I was coding this [pin model exporter PR](https://github.com/Origen-SDK/origen/pull/172) I realized that the pin model has some [hardcoded metadata based on package scope](https://github.com/Origen-SDK/origen/blob/master/lib/origen/pins/pin.rb#L12).  Whereas, the pin model has [function scoped hard coded meta data and a catch-all 'meta' attribute (a hash)](https://github.com/Origen-SDK/origen/blob/master/lib/origen/pins/pin.rb#L8).  When I wrote my pin importer, I noticed  at least a dozen package scoped attributes that I had no place to store.  I guess this question could apply to any model:

How do we plan to store meta data that can be scoped at various levels within a model.  My first thought was to extend the concept of a 'meta' hash that can be scoped to various levels (as is currently done in the pin function scope) within a model.   This is a pretty urgent item for our app as we have metadata that can not be currently modeled.

thx

**Comment by ginty** [comment]
I think adding model.meta which would behave like pin.meta as shown here would be a good addition:
http://origen-sdk.org/origen//guides/models/pins/?highlight=meta#Pin_Functions

i.e. the meta hash could be accessed at any model in the hierarchy but values defined lower down would override those defined by the parent/ancestors.

I think we mean the same thing here.

**Comment by info-rchitect** [comment]
@ginty would we have to make a hierarchy call between function attributes and package attributes with the same name (e.g. meta)?  Perhaps the best short term solution is to add 'dib_meta' to the package scoped attributes as a hash?

**Comment by info-rchitect** [comment]
attempt to fix [here](https://github.com/Origen-SDK/origen/pull/174)
