### ISSUE TITLE
Quick question on Limits

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#178]
I would like folks to weigh in on whether a LimitSet (:min, :typ, :max) is a Class that would reside in the namespace of Origen::Specs::Spec or if a LimitSet can be defined outside of a specification?  I am asking for an urgent response as this will help clarify my initial Origen::Specs RFC.  I have a forked version of the Specs module that has limit sets working but need this answer before sharing on github.  thx

**Comment by chrisnappi** [comment]
Sorry - but is this the limits FOR :min, :typ, :max voltages - like the ADC INL for min VDD, or are these the limits themselves and an assumed typical?  I find it confusing to mix conditions and limits, and there for always use 'lsl' and 'usl' for 'lower side limit' and 'upper side limit'.

**Comment by info-rchitect** [comment]
@chrisnappi Currently there is not concept of a limit set at all within Origen.  Indirectly the Spec class has min, typ, max limits which are instantiations of the Origen::Specs::Spec::Limit struct.  But now that we are moving to allow a Spec to have infinite limit sets the question came up about scope.  

Some people might not want to use Origen::Specs to handle their specs but rather just roll their own in Origen::Parameters. Wouldn't those folks be entitled to LimitSets the same as those who use Origen:;Specs?  I hope this makes my question clearer.

**Comment by info-rchitect** [comment]
OK well no overwhelming ideas either way so I kept the LimitSet class within the Specs module.

~~~ruby
module Specs
  module Limits
    class LimitSet
      include Limits

      attr_accessor :id, :min, :typ, :max, :description
      
      def initialize(id = nil, &block)
        @id = id.nil? ? :datasheet : id
        (block.arity < 1 ? (instance_eval(&block)) : block.call(self)) if block_given?
        @description = description
        @min = Limit.new(min)
        @typ = Limit.new(typ)
        @max = Limit.new(max)
      end
~~~

Here is an interactive session with the new spec limits sets:

~~~ruby
[1] pry(main)> dut.jtag.specs(/vol/).current_limit_set
=> :datasheet
[2] pry(main)> dut.jtag.specs(/vol/).limit_sets
=> [:datasheet]
[3] pry(main)> dut.jtag.specs(/vol/).limits
=> #<Specs::Limits::LimitSet:0x002b8a9d557708
 @description=nil,
 @id=:datasheet,
 @max=#<struct Specs::Limits::Limit exp="0.2 * :vdda">,
 @min=#<struct Specs::Limits::Limit exp=nil>,
 @typ=#<struct Specs::Limits::Limit exp=nil>>
[4] pry(main)> dut.jtag.specs(/vol/).add_limit_set :skew do |s|
[4] pry(main)*   s.max = 0.5
[4] pry(main)*   s.description = "Process skew limits for certain lots"
[4] pry(main)* end
=> #<Specs::Limits::LimitSet:0x002b8a9c8a56e0
 @description="Process skew limits for certain lots",
 @id=:skew,
 @max=#<struct Specs::Limits::Limit exp=0.5>,
 @min=#<struct Specs::Limits::Limit exp=nil>,
 @typ=#<struct Specs::Limits::Limit exp=nil>>
[5] pry(main)> dut.jtag.specs(/vol/).limit_sets
=> [:datasheet, :skew]
[6] pry(main)> dut.jtag.specs(/vol/).limits = :skew
=> :skew
[7] pry(main)> dut.jtag.specs(/vol/).limits
=> #<Specs::Limits::LimitSet:0x002b8a9c8a56e0
 @description="Process skew limits for certain lots",
 @id=:skew,
 @max=#<struct Specs::Limits::Limit exp=0.5>,
 @min=#<struct Specs::Limits::Limit exp=nil>,
 @typ=#<struct Specs::Limits::Limit exp=nil>>
~~~

**Comment by ginty** [comment]
Isn't this the kind of thing that should be discussed in the RFC?

Seems a bit premature to call time on it in < 24 hrs, especially when we are talking about re-working something which has already proved inadequate.

**Comment by ginty** [comment]
Personally, I would see Spec and Limit be siblings of each other, both would be some kind of wrapper around the Attribute objects I describe here: https://github.com/Origen-SDK/origen_testers/pull/73#issuecomment-347189616

**Comment by info-rchitect** [comment]
@ginty i am just calling time on this quick question about one aspect of the RFC.  it will all be open to rehash in the RFC.

**Comment by info-rchitect** [comment]
@ginty we are using these new features as they are coded so this is urgent for us, probably much more so than the general community.  Trying to balance the fine line of pushing code to the general community and getting stuff done :)  Using our own internal version has major disadvantages so we want to convert to a generally accepted solution very soon.
