### ISSUE TITLE
Origen home_dir site config variable

### ISSUE THREAD

**Issue by coreyeng** [Origen-SDK/origen#183]
Following the discussion from PR #181 I'd like to open the topic of having the home_dir site config auto-append some user specifics.

My intention of this was to adequately move the entire 'user install directory' to somewhere else. This was intended to be a global site-config setting, essentially fully switching ~/.origen to home_dir. Currently, it will accomplish this and can be done for a single user effectively, but it can't be set by a origen install manager as originally intended, as then everyone will end up with home_dir and start stepping on each other.

My proposal is to auto-append, the username to home_dir, rendering home_dir as just a root path. For example:

- home_dir: ~/ #=> (default) Creates Origen user installation at ~/.origen
- home_dir: /proj/origen_workspaces #=> (set in site config for example) Create user installations at /projge/origen_workspaces/<whoami>/.origen

I could add another site variable (maybe disable_home_dir_appendix) that would disable this, but in that case I had the user_install_dir, user_gem_dir, user_install_enable site configs to handle this.

Please let me know what your thoughts are on this. I want to balance customization, usefulness, and clarity. I always use the combo user_install_dir, user_gem_dir, and user_install_enable, so I'm not sure how others are looking to use this and what results they are expecting.

Once I've gathered feedback I'll start implementing.

@ginty, per your notes from PR #181 

- Remove gem_install_dir from the example site_config
Corey: I will do this for this issue. I also added a deprecation note in the docs saying this will be overruled if 'user_gem_dir' is also present.
- Put comments on that method telling us that while internally Origen still calls it site_config.gem_install_dir, it is intentional that the value no longer originates from the config variable of the same name.
Corey: I'll redo the comments for clarity in site_config.rb.
- Put clear documentation somewhere in the getting started section describing how an average user can easily change where their gems live, (we didn't have this before admittedly with gem_install_dir, but things were much simpler then than they are now). Bottom line, no one should need to go near that advanced page if all they want to do is change their gem dir.
Corey: Updated the docs for PR #181 but will make a second pass though those docs with this issue.
- user_install_dir should probably be mentioned somewhere in the advanced guide, I just assumed that it didn't really exist given that we have all that documentation and it doesn't even mention it.
Corey: Will do for this issue.
- We really should be making this backwards compatible with anyone who already has $ORIGEN_GEM_INSTALL_DIR defined
Corey: Completed by you in PR #181

**Comment by ginty** [comment]
Hi @coreyeng, thanks for following up on this.

Not sure that forcing an append makes sense, I think using Linux variables, like `~/` is still a good and reasonable default.

Why don't you just allow `@user` to be written into the path and gsub it in the `gem_install_dir` and `user_install_dir` methods?

**Comment by coreyeng** [comment]
I would leave <code>~/</code> as the default, I agree. I don't think I could use <code>@user</code> since Origen would evaluate the paths prior to <code>@user</code> being defined. I think that doing that anyway would result in about the same, wouldn't it? Just making a custom <code>home_dir</code> also contain the user's ID? Like having <code>home_dir: /proj/origen_workspaces/</code> resolve to <code>/proj/origen_workspaces/coreyeng/.origen</code> for me.

**Comment by ginty** [comment]
Well, by "@user" I just meant a variable representing the user ID, not an Origen user object.

You will have to work out the user ID somehow anyway, so I am just suggesting that we give the installer controller over where the user ID is injected in the path, if at all, rather than enforcing it at the end.

**Comment by coreyeng** [comment]
Okay. I understand then. What do you think of using <code>~</code> instead? 

For example: <code>home_dir: /proj/users/~/workspaces</code> #=> <code>/proj/users/coreyeng/workspaces/.origen</code>

**Comment by ginty** [comment]
That's fine by me if you prefer

**Comment by coreyeng** [comment]
Covered in #207
