### ISSUE TITLE
Proposal to make separate files for sub_blocks/regs and package/pins in model export

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#184]
All,

As we have been using the model exporter (thx @ginty) we would like to propose that the IP blocks and registers be put in a separate export file from the package and pins.  The reason for this is simply to allow more precision when specifying dynamic loading using target files or command line options to Origen commands.  

We would also like the ability to change where an application looks for its models versus hard-coding the vendor path.  This again is due to run-time issues.  For one of our larger products it takes over 1 hr to import and export the files to Origen (mostly on export BTW), consuming 951MB of space.  We really don't want the average user to have to ever worry about importing data and only see the models in action.  A team lead would create the models in the local app vendor path and then copy the files to an /origen disk with product specific repos.  This saves time for the whole engineering teams, simplifies the user experience, and reduces errors.

I will handle the PR but wanted to get some feedback before starting.

regards

**Comment by ginty** [comment]
Sounds good re. the alternative load path option.

Not sure I follow with regards to the benefit of splitting the regs out to a separate file though.

**Comment by info-rchitect** [comment]
@ginty the benefit is purely organizational, the same thing could be accomplished with the same file and various options for export and import.  But our app is designed to work for all products and it heavily relies on segregating and namespacing various types of models.  Since we want to store the large amount of Origen source files on a common disk, we didn't want people having to dig through a 10k+ line file to separate out registers, sub_blocks and pins.

**Comment by info-rchitect** [comment]
PR will end up being to allow separate load path, not separate files.
