### ISSUE TITLE
on_create of controller class not called for Origen v0.28+

### ISSUE THREAD

**Issue by Dieleman** [Origen-SDK/origen#186]
Upgrading from v0.27.0 to version 0.28.0 or 0.28.1 breaks the on_create() call to (at least one) controller class. Since pin_aliases are defined in my on_create method, these pins can now no longer be found.

By briefly looking through the commits it was for me not clear what is causing this.

Changing back to v0.27.0 fixes this.

**Comment by ginty** [comment]
Fixed here: https://github.com/Origen-SDK/origen/pull/190

**Comment by ginty** [comment]
Fixed in 0.28.2
