### ISSUE TITLE
Proposal to remove app name from model exporter

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#189]
All,

I made a PR the other day to allow users to import models from any path they want.  However, that doesn't work as the model exporter puts the app name in the relative path in the .rb files as such:

~~~ruby
model.sub_block :my_ip, file: 'ppe_kit/myprod/my_ip.rb'
~~~

I would like to propose we just remove the application name from this relative path so users can export to vendor, move the files, and then import from a new path without having to put the app directory where it really isn't needed IMO.  

~~~ruby
model.sub_block :my_ip, file: 'myprod/my_ip.rb'
~~~

Thoughts?

**Comment by ginty** [comment]
Seems reasonable

**Comment by info-rchitect** [comment]
https://github.com/Origen-SDK/origen/pull/188
