### ISSUE TITLE
Remotes feature should be updated to use abstract revision control API

### ISSUE THREAD

**Issue by ginty** [Origen-SDK/origen#19]
The remotes feature should be updated to use the abstract RC API under the hood:
http://origen-sdk.org/origen/guides/misc/revisioncontrol/

This will update the remotes feature to work with any RC tool supported by Origen.

Also please update the remotes guide to use this API to reference the path to the imported data:
http://origen-sdk.org/origen/release_notes/#v0_5_6

**Comment by rlaj** [comment]
Implemented in PR #78. Closing.
