### ISSUE TITLE
Origen and SWIG?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#206]
Hi,

Many companies have fast, useful libraries built in C and C++ that are both internal and customer facing.  Has anyone else have the need to integrate such libraries into Ruby?  I believe [SWIG](http://www.swig.org/Doc1.3/Ruby.html#Ruby_nn2) is one of the solutions.  Has anyone used SWIG or any other solution?  The end result for us would be to start the C model and query it from Origen to get product specific metadata, versus having to export the model data to an XML/JSON format.

thx

**Comment by ginty** [comment]
Yes SWIG is a viable route for this, this is what we used in NXP to create Ruby bindings to one of our internal C-based tools that I think you might be familiar with (TPC) and it worked perfectly.

I wasn't involved in the SWIG side of things though so can't really help with that, but it certainly doesn't require anything Origen-specific and it is essentially a case of compiling the C-project through SWIG to create a shared object that targets Ruby.

So for example, let's say your C library is called MyDevices, and it provides a function like this:

~~~c
int sizeOfRAM(string product) {
  if (product == "prod-x") {
    return 1024;
  else if (product == "prod-y") {
    return 2048;
  }
} 
~~~

The you would compile that through SWIG to create `my_devices.so`, then you could use it in Ruby something like this:

~~~ruby
require "path/to/my_devices.so"

MyDevices.sizeOfRAM("prod-x")   # => 1024
~~~

It's pretty neat actually.

**Comment by info-rchitect** [comment]
thx @ginty, the work is underway.  maybe a blog sometime soon...
