### ISSUE TITLE
Origen parameter sets not able to define all Verigy test method parameters

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#208]
Hi,

We have some test method parameters that seem to be mutually exclusive when using Origen::Parameters::Set.  Here are two test method parameters that we cannot currently define at the same time:

~~~ruby
        p.tm.Scan_FailDataControl_UseDebugParams = true
        p.tm.Scan_FailDataControl_UseDebugParams_FrequencyVariable = 'shift_freq'
~~~

I understand why this is occurring, the 'UseDebugParams' part of the parameter hierarchy gets set to true and cannot be used as a 'hash'.  We have multiple occurances of this within our library and I do see examples of this same issue using a default SmartTest v7 test method definition:

~~~shell
testmethod 20 -- multi_group_dc_tml.DcTest.Leakage
  location name: "Leakage.cpp:Leakage"
  shared lib path: "/opt/hp93000/soc/segments/tml/sh_lib/libmulti_group_dc_tml.so"
  source project path: ""
  compiled with SmarTest version: "7.3.2.11, 05-Jul-16"
  parameter ids:
    UsePPMU :string, YES
    UsePPMU.pinlist :PinString, 
~~~

Is anyone using Origen parameter sets to define test method parameters?  If so, have you run into this issue?  If so, how did you workaround it?

thx

**Comment by ginty** [comment]
What if you define them the other way round?

**Comment by info-rchitect** [comment]
@ginty that did work, thx.  I will submit a PR to highlight this corner case in the docs.

**Comment by ginty** [comment]
Does seem like a bug though, we should leave this open.

I don't really understand what's going on here, but just looking at your example I would expect that to work as written.

**Comment by info-rchitect** [comment]
@ginty sorry I had put an incorrect version of the parameter definition.  Here is the version that causes the issue:

~~~ruby
        p.tm.Scan.FailDataControl.UseDebugParams = true
        p.tm.Scan.FailDataControl.UseDebugParams_FrequencyVariable = 'shift_freq'
~~~

It only occurs when a period is used in the parameter definition.

**Comment by info-rchitect** [comment]
@ginty we moved to using underscores but wanted to make sure this issue was resolved (if it is an issue).
