### ISSUE TITLE
What's in the exported model files?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#219]
Hi,

An issue has come up in our app regarding the exported model files and I wanted to share it, as I think people could run into the same thing eventually.  Given the size of our model, we dynamically load pieces of it based on an array of test module dependencies.  So depending on what test modules the user uses during the first export, various pieces of the model exist (sometimes just pins, sometimes just sub_blocks, etc.).  Our app checks the existence of the file to determine if a forced import is necessary but that is not enough as the exported file may still not contain the model pieces required.  I really only see three options currently:

1. Export everything no matter what.  This will work for sure but is not ideal as the import/export process takes > 4hrs for one of our products.
2. Export the model into separate files, one for sub_blocks, one for pins, etc.
3. Parse the exported file for pins, sub_blocks, etc.

Thoughts?

**Comment by ginty** [comment]
Is this not more a question around how you import rather than export?
i.e. no matter what the export strategy is, it won't be able to export anything that has not been imported yet.

**Comment by info-rchitect** [comment]
@ginty well yes it is.  I take it you are n favor of options #1?

**Comment by info-rchitect** [comment]
So in the need for a quick solution, I don't think option #3 is all that bad.  As I said we have a model vocabulary (e.g. :pins, :regs, etc.) that dictates what gets loaded.  This code worked as a solution to #3:

~~~ruby
    def exported_models_exist?(model_types = nil)
      model_path = Pathname.new("#{Origen.root}/vendor/lib/models/ppe_kit/#{current_product_name.downcase}_#{current_product_revision}.rb")
      if model_types.nil?
        model_path.exist? ? true : false
      else
        possible_exported_models = [:pins, :regs]
        models_to_check = possible_exported_models & model_types
        models_to_check.each do |m|
          str = case m
          when :regs
            'model.sub_block'
          when :pins
            'model.add_pin'
          end
          return false unless File.readlines(model_path.to_s).grep(/#{str}/).any?
        end
      end
    end
~~~

If people find this useful, I could add this to Origen core.

regards

**Comment by ginty** [comment]
I don't really have a preference, this seems like an application concern.
i.e. Origen should already support only importing the regs and then exporting them, and then doing the same with the pins separately if you want.
Application logic being in charge of what/when you import seems right to me.
