### ISSUE TITLE
Reload of DUT multiple times an issue for v1.0?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#232]
All,

As adoption of Origen increases here many folks are complaining about the reloading of the DUT multiple times.  I am sure there are things I can do to lessen the impact on our app side but the consensus in our last users group was that we needed a clear explanation on why this is necessary, in documentation.  Obviously this is not a priority one issue but I wanted to get it out there.  Is it due to legacy apps or is there really a fundamental Origen reason why this occurs.

thx

**Comment by ginty** [comment]
The background to that is as given here: https://github.com/Origen-SDK/origen/issues/114#issuecomment-326230237

**Comment by ginty** [comment]
We can definitely consider changing it though

**Comment by info-rchitect** [comment]
thanks @ginty .  I will forward folks to our previous conversation.  I am trying to get a list of issues, as @welguisz  did, that should be part of our v1.0 list.  Is a v1.0 RFC the right place?

**Comment by ginty** [comment]
Should open an issue fir each one and assign a v1 label to them I think

**Comment by info-rchitect** [comment]
@ginty OK, i will make a pass at the issues this weekend and folks can review.
