### ISSUE TITLE
FYI: Change in Github crypto policy

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#233]
https://githubengineering.com/crypto-removal-notice/

This has left us temporarily down...

**Comment by priyavadan** [comment]
I believe we at NXP should be okay. I think the new NXP datacenter uses RedHat 6/7, will need to check the git version installed.  Will update later today!

**Comment by info-rchitect** [comment]
@priyavadan yeah this really sucks as I was in the middle of the mother of all releases, impacting 4 repos, and suddenly could not get my latest origen fork.  And I have a feeling we may require an all new OS upgrade on top of some other stuff.  :/

**Comment by ginty** [comment]
Cloning via ssh should be OK regardless I think

**Comment by info-rchitect** [comment]
@ginty it is much worse than I thought, we have multiple things that Github does not like:

~~~
peologin02:origen $ ssh -T git@github.com
no kex alg
peologin02:origen $ ssh -Vxx
OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
~~~

**Comment by redxeth** [comment]
Strange.  git pull works for me.  I cloned using HTTPS not SSH.  @priyavadan came by and figured out that I was using a different version of git (1.7.7.4) than he was (2.7.2).  In our setup the version is different depending if you've run the rgen setup env script we use.

**Comment by priyavadan** [comment]
@redxeth thanks! yes it looks like the default git version provided by NXP IT using TR-DYNAMIC (1.7.7.4) works fine. 

We will have to figure out a workaround internally, I think I have an idea

**Comment by priyavadan** [comment]
NXP Folks, I have a workaround so please send me an IM if/when you run into an issue.

![image](https://user-images.githubusercontent.com/3895377/36603219-bab83b84-187f-11e8-86ce-297ee6b51461.png)

**Comment by priyavadan** [comment]
Also as @ginty mentioned, I just confirmed that cloning via SSH also works.

![image](https://user-images.githubusercontent.com/3895377/36603348-10874622-1880-11e8-8abf-81c394945859.png)
