### ISSUE TITLE
Gems without nokogiri cannot compile web docs

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#259]
Hi,

Here is the error:

~~~shell
Loading site data\u2026 
Captain! We\u2019ve been hit!

Message:

LoadError: cannot load such file -- nokogiri
Make sure the gem is added to Gemfile and run `bundle install`.

Compilation stack:

  (empty)

Stack trace:

  0. lib/bootstrap_filter.rb:1:in `require'
  1. lib/bootstrap_filter.rb:1:in `<main>'
  2. /home/bcaqueli/.origen/gems/ruby/2.3.0/gems/nanoc-3.8.0/lib/nanoc/base/source_data/code_snippet.rb:34:in `eval'
~~~

I did a recursive grep and the only difference between gems that can compile web docs and those that cannot is the lack of nokogiri being in the Gemfile.lock.

~~~text
# gem that can compile webdocs
,yserver $ grep -ri nokogiri *
Gemfile.lock:      nokogiri (>= 1.4.1)
Gemfile.lock:    nokogiri (1.8.2)
Gemfile.lock:      nokogiri (~> 1)
lbin/nokogiri:# The application 'nokogiri' is installed as part of a gem, and
lbin/nokogiri:load Gem.bin_path("nokogiri", "nokogiri")
web/lib/bootstrap_filter.rb:require 'nokogiri'
web/lib/bootstrap_filter.rb:    doc = Nokogiri::HTML.fragment(content)
web/lib/bootstrap_filter.rb:    Nokogiri::HTML(html).css("div")
web/lib/codeblocks_filter.rb:require 'nokogiri'
web/lib/codeblocks_filter.rb:    doc = Nokogiri::HTML.fragment(content)
web/lib/search_filter.rb:require 'nokogiri'
web/lib/search_filter.rb:    doc = Nokogiri::HTML(content)

# gem that cannot compile web docs
pmyserver $ grep -ri nokogiri *
lbin/nokogiri:# The application 'nokogiri' is installed as part of a gem, and
lbin/nokogiri:load Gem.bin_path("nokogiri", "nokogiri")
web/lib/bootstrap_filter.rb:require 'nokogiri'
web/lib/bootstrap_filter.rb:    doc = Nokogiri::HTML.fragment(content)
web/lib/bootstrap_filter.rb:    Nokogiri::HTML(html).css("div")
web/lib/codeblocks_filter.rb:require 'nokogiri'
web/lib/codeblocks_filter.rb:    doc = Nokogiri::HTML.fragment(content)
web/lib/search_filter.rb:require 'nokogiri'
web/lib/search_filter.rb:    doc = Nokogiri::HTML(content)
web/crash.log:LoadError: cannot load such file -- nokogiri

Seems like we need some new Gemfile mode that enables nokogiri during web compile.  Anyone know how to do this?

thx

**Comment by coreyeng** [comment]
You should be able to bring in nokogiri yourself and those gems will work. I had a similar problem with my IAR plugin when I updated Origen versions and I included nokogiri in the application Gemfile to fix it. Origen doc helpers probably needs to be updated to pull in nokogiri itself since Origen no longer will. Or, we add nokogiri back to the gemspec with just open conditions (no min/max version).

**Comment by coreyeng** [comment]
Seems that if Origen doesn't actually need it though, just other things that depend on Origen need Nokogiri, then those other things should be pulling it in, not Origen itself.

**Comment by info-rchitect** [comment]
@coreyeng I don't think it is the gems responsibility because the web docs use some gem themselves right?  Shouldn't that gem handle making sure it has nokogiri?

**Comment by coreyeng** [comment]
Yes, you are correct. I was thinking the web filter stuff was in origen_doc_helpers, in which case, origen_doc_helpers should bring in Nokogiri. Doing a search on the origen repo, specs are also reliant on Nokogiri, so we should be bringing in Nokogiri in Origen (or ship this stuff out to other/separate plugins who will require nokogiri).

**Comment by ginty** [comment]
I've noticed this too, it seems the Origen did actually depend on nokogiri.

I think we should add an nokogiri >= 1.7.2 into Origen's gemspec

**Comment by info-rchitect** [comment]
@coreyeng yep
