### ISSUE TITLE
origen test fails is user specifies where to install gems

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#261]
~~~ruby
  7) Origen.site_config Site config install directories with ENV variables set with ORIGEN_GEM_INSTALL_DIR set uses the value in ORIGEN_GEM_INSTALL_DIR instead of :gem_install_dir
     Failure/Error: expect(Origen.site_config.user_gem_dir).to eql("/env/gem/.origen/gems")
     
       expected: "/env/gem/.origen/gems"
            got: "/users/user/origen/.origen/gems"
     
       (compared using eql?)
     # ./spec/site_config_spec.rb:243:in `block (4 levels) in <top (required)>'
     # ./config/commands.rb:42:in `<top (required)>'
     # ./lib/origen/commands.rb:185:in `require'
     # ./lib/origen/commands.rb:185:in `<top (required)>'
~~~

When travis runs the same build it passes.

**Comment by coreyeng** [comment]
Do you have any other Origen environment variables set? This is assuming a blank ENV and I think <code>context</code> restarts the process in specs, so it may be a spec bug where I need to clear the environment, not just the site config.

Travis wouldn't have ENV variables set, so it won't affect it there. I will try to replicate it.

**Comment by coreyeng** [comment]
To expand a bit, the context setup should override <code>ORIGEN_GEM_INSTALL_DIR</code>but it won't clear <code>ORIGEN_USER_GEM_DIR</code>, so that may be throwing it off if you have it set.

If so, its a bug in the spec setup that I'll correct.
