### ISSUE TITLE
Getting deprecation warning even though my app has origen_testers

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#264]
Here is the warning:

~~~shell
peologin07:ppekit $ origen p scan_flow.rb
[INFO]       7.473[0.063]    || **********************************************************************
[DEPRECATED] 7.489[0.016]    || Origen core will no longer support program generation in v1, add the origen_testers plugin to your application to fix this warning
[DEPRECATED] 7.490[0.001]    || Called by /users/user/origen/prod/ppekit/program/scan_flow.rb:1
~~~

Here is my app's Gemfile:

~~~ruby
gem 'origen_testers', git: 'ssh://git@stash.mycompany.com:7999/osdk/origen_testers.git', ref: '0.20.0'
~~~

**Comment by ginty** [comment]
I think this is temporary because you are running latest Origen with an old Origen testers.
When you update to a latest OrigenTesters it should go away.

**Comment by info-rchitect** [comment]
@ginty what do you mean an old veersion of origen_testers?  isn't 0.20.0 the latest?

**Comment by ginty** [comment]
Ah, you are right, thought we were in the 30s

**Comment by ginty** [comment]
Seems that the corresponding update to OrigenTesters is in the smt8 branch, should be merged within a couple of weeks

**Comment by info-rchitect** [comment]
@ginty OK sounds good
