### ISSUE TITLE
Origen.app! not returning plugin's application instance

### ISSUE THREAD

**Issue by rkoripalli** [Origen-SDK/origen#273]
I'm trying to access an instance variable stored in a plugin's application.rb file from the plugin's interface. I put a binding in the plugin's interface and ran Origen.app and [Origen.app!](http://origen-sdk.org/origen/api/Origen.html#app!-class_method) from pry. The expected result is for Origen.app to return the main application and [Origen.app!](http://origen-sdk.org/origen/api/Origen.html#app!-class_method) to return the plugin's application instance since it is being called from the plugin's interface. The actual result is that Origen.app! also returns the main application rather than the plugin's application instance.

This is the code in the application.rb file
 
```
attr_accessor :create_limits_tables

@create_limits_tables = false
```

```
[4] pry(#<MyTest::Interface>)> Origen.app! == Origen.app
=> true
```

**Comment by coreyeng** [comment]
Hello,

I'm not familiar with using pry, but if its similar to <code>origen i</code>, then running <code>origen i</code> from within your application or using <code>Origen.app</code> and <code>Origen.app!</code> from within the same application will result in those being equivalent. The difference only occurs when <code>Origen.app!</code> is used within the context of the plugin. <code>Origen.app!</code> will change to whatever context its being called in.

To see the config variables for the plugin from within your current app, or using <code>origen i</code>, you can do something along the lines of: <code>Origen.app.plugins.find { |pl| pl.name == :my_plugin }.config</code> to get your plugins configuration attributes. 

Another thing to note though, is that instance variables directly in <code>config/application.rb</code> are not on the plugin but on the plugin's application. Do you mean that this on a file <code>lib/application.rb</code>, or something similar? 

If none of that helps, we (or at least I, maybe someone else will know) will need more details on what you're trying to do. I'm currently working on an updated feature that uses <code>Origen.app</code> and <code>Origen.app!</code> and it seems to be working correctly for me, though that doesn't mean there's not some bug you've exposed:

~~~ruby
# plugin1/config/application.rb

config.shared_pattern_header do
  "Hi from shared #{Origen.app!.name}!"
end

config.current_plugin_pattern_header do
  "Hi from current plugin: #{Origen.app!.name}!"
end

# plugin2/config/application.rb

config.shared_pattern_header do
  "Hi from shared #{Origen.app!.name}!"
end

config.current_plugin_pattern_header do
  "Hi from current plugin: #{Origen.app!.name}!"
end

# my_app/config/application.rb

config.shared_pattern_header do
  "Hi from application #{Origen.app!.name}!"
end
~~~

I also don't see that we have the config attributes in our guides, but it is in the [API](http://origen-sdk.org/origen/api/Origen/Application/Configuration.html)

Then you can use <code>config.add_attribute(:create_limits_tables)</code> then get its value from your application using </code>Origen.app.plugins.find { |pl| pl.name == :my_plugin }.config.create_limit_tables</code>.

Thanks,

Corey

**Comment by ginty** [comment]
Thanks for reporting this @rkoripalli.

Like Corey, I suspect that this may be an artifact of using pry, however can you confirm a few details about your setup?

I don't use pry either, but this means that you are executing this within the context of something like `lib/my_test/interface.rb` ?

~~~text
[4] pry(#<MyTest::Interface>)> Origen.app! == Origen.app
=> true
~~~

Also, how did you get to that point in the code? Do you have a top-level app and your plugin setup via a path as shown here and then put a binding call in there directly? - http://origen-sdk.org/origen/guides/plugins/environment/

Or is your plugin installed regularly and you put the binding call in your top-level app code and then stepped through to the plugin interface code?

**Comment by ginty** [comment]
@rkoripalli, I'm closing this because we haven't heard back from you and I assume that means it has been resolved on your side.

Otherwise, we are not sure what to fix/change since we have tests for this and it seems to work fine in other applications.

If it is still a problem please feel free to re-open it.
