### ISSUE TITLE
Bootsnap gem for app loading performance

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#288]
https://github.com/Shopify/bootsnap

any thoughts?

**Comment by pderouen** [comment]
This comment (first sentence in the section) seems to imply that it doesn't work on Windows which would be a show stopper:
https://github.com/Shopify/bootsnap#usage

**Comment by info-rchitect** [comment]
@pderouen Why would that be a show stopper?  I think Bootsnap is application specific.

**Comment by ginty** [comment]
This does actually seem to work, seems to speed up the time to load the app and target in one of my apps by ~2.2s, going from 5.5s down to 3.2s:

~~~text
stephen@NXL78024:~/Code/bitbucket/c402t_nvm_tester$ time origen nvm:build
App and target loaded!

real    0m5.427s
user    0m1.250s
sys     0m3.891s
stephen@NXL78024:~/Code/bitbucket/c402t_nvm_tester$ time origen nvm:build
App and target loaded!

real    0m5.463s
user    0m1.297s
sys     0m3.906s
stephen@NXL78024:~/Code/bitbucket/c402t_nvm_tester$ time origen nvm:build
App and target loaded!

real    0m5.613s
user    0m1.422s
sys     0m3.828s
~~~

Now with bootsnap:

~~~text
stephen@NXL78024:~/Code/bitbucket/c402t_nvm_tester$ time origen nvm:build
App and target loaded!

real    0m3.160s
user    0m0.859s
sys     0m2.109s
stephen@NXL78024:~/Code/bitbucket/c402t_nvm_tester$ time origen nvm:build
App and target loaded!

real    0m3.232s
user    0m0.766s
sys     0m2.203s
stephen@NXL78024:~/Code/bitbucket/c402t_nvm_tester$ time origen nvm:build
App and target loaded!

real    0m3.404s
user    0m0.906s
sys     0m2.172s
~~~

**Comment by info-rchitect** [comment]
@ginty thx for trying it, I was going to get to it in the next week or two during a refactor.  Are you going to use it?

**Comment by ginty** [comment]
I think I would vote to add it to Origen based on those performance numbers.

It really needs to be added to Origen though and not at app-level so that you get the benefit of it when loading Origen and your app's plugins.

It's easy enough to inhibit it from kicking in on Windows, the only thing is that we need to make sure that including bootsnap as an Origen dependency does not break it on Windows.

@pderouen, could you please check if running 'gem install bootsnap' works on Windows or not?

**Comment by pderouen** [comment]
Success:
PS C:\> gem install bootsnap
Fetching: msgpack-1.2.4-x64-mingw32.gem (100%)
Successfully installed msgpack-1.2.4-x64-mingw32
Fetching: bootsnap-1.3.2.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions. This could take a while...
Successfully installed bootsnap-1.3.2
Parsing documentation for msgpack-1.2.4-x64-mingw32
Installing ri documentation for msgpack-1.2.4-x64-mingw32
Parsing documentation for bootsnap-1.3.2
Installing ri documentation for bootsnap-1.3.2
Done installing documentation for msgpack, bootsnap after 1 seconds
2 gems installed

**Comment by info-rchitect** [comment]
w/o bootsnap:

~~~shell
real    1m0.397s
user    0m35.132s
sys     0m2.421s
~~~

~~~shell
w/bootsnap
real    0m44.455s
user    0m36.764s
sys     0m2.451s
~~~

**Comment by ginty** [comment]
Added to v0.36.0
