### ISSUE TITLE
Reloading of the DUT model for v1.0

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#290]
All,

As Origen spreads and people create very large characterization flows with it, the general feedback is that it takes too long to run (some flows take > 1hr, most in the 3-10 minute range).  I know some of that is due to the way I built our app (no autoload).  I am currently working on that but the gorilla in the room is the multiple reloading of the DUT model.  I believe it takes a minimum of 3 DUT re-loads per flow generation.  Can we make this optional?  Not only would this save time but it would allow initial arguments to be retained easier.

thx

**Comment by info-rchitect** [comment]
any comments here?  This really is the only Achilles heal for Origen when viewed by folks with larger chips.

**Comment by info-rchitect** [comment]
closing as we have got our boot time to < 1s with lazy instantiation and also used 'preserve target' when using the compiler.

**Comment by ginty** [comment]
> closing as we have got our boot time to < 1s with lazy instantiation and also used 'preserve target' when using the compiler.

@info-rchitect, nice!
