### ISSUE TITLE
Compiler is very slow

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#297]
Hi,

We love the compiler except for the performance time.  I just created a 13 line file that took over 30s.

~~~ruby
% options[:softbins].each do |sbin_descp, sbin|
        <SoftBin id="<%= sbin%>" desc="<%= sbin_descp%>" />
% end
~~~

~~~shell
[INFO]       38.250[0.008]   || **********************************************************************
[INFO]       38.260[0.010]   || Compiling... ../../../test/templates/ate/binning_ws.xml.erb
[INFO]       38.261[0.001]   ||   Created... ../jtag/origen/ws1/jtag_ws1_HBXX_Binning.xml
[INFO]       74.649[0.032]   || **********************************************************************
[SUCCESS]    74.649[0.000]   || Total files:      1
[SUCCESS]    74.649[0.000]   || New files:        0
[SUCCESS]    74.649[0.000]   || Changed files:    0
~~~

I believe this is due to reloading the DUT model.  Can someone verify this and if so, explain why this is necessary?

thx

**Comment by ginty** [comment]
Possibly there is a double load in there that could be removed, but I would first reflect the question back to you - why does you target take so long to instantiate?

**Comment by info-rchitect** [comment]
@ginty There are many reasons the target takes a lot of time to load, some we can control (some recursive methods we are optimizing) and some we cannot (sheer size).  However, I did find that passing `preserve_target: true` [prevents the target from getting reloaded.](https://github.com/Origen-SDK/origen/blob/master/lib/origen/generator/compiler.rb#L140).  We would still like Origen to stop reloading the target after the 1st load in the future or at least make it optional.

**Comment by pderouen** [comment]
I have noticed the double load of the DUT. It's very obvious when link is the tester. It winds up sending init commands twice.

I shared my app load times from my windows machine. It's typically ~15 seconds or more. Bootsnap and moving the model to the best practice method for loading didn't really help.

**Comment by info-rchitect** [comment]
https://stackoverflow.com/questions/52950896/can-the-compiler-avoid-reloading-the-target

**Comment by ginty** [comment]
Btw, `preserve_target` is a valid and official way to improve template compilation performance, it is documented here - https://origen-sdk.org/origen//guides/compiler/subtemplates/?highlight=preserve_target#A_Note_on_Performance

**Comment by pderouen** [comment]
I agree. Just haven't figured out how to load it better just yet.

**Comment by info-rchitect** [comment]
@ginty we will gladly make the patch if someone could provide some touch points on where we might look.

**Comment by ginty** [comment]
I'm kinda taking your work for it that it is doing multiple loads, but its not obvious to me if it is, here at least is the first one that it does - https://github.com/Origen-SDK/origen/blob/master/lib/origen/commands/compile.rb#L59

You should architect your model to lazy load these fuses and so on:

~~~ruby
# Don't do this
def initialize(options = {})
  @fuses = instantiate_my_fuses
end

# Do this
def fuses
  @fuses ||= instantiate_my_fuses
end
~~~

**Comment by welguisz** [comment]
I would suggest using rbspy to figure out exactly which functions are causing the longest time.  

Github:  https://github.com/rbspy/rbspy
Documentation: https://rbspy.github.io/

**Comment by info-rchitect** [comment]
thanks for the tips everyone, will report back on the other issue regarding multiple loads.
