### ISSUE TITLE
Parameter sets now throwing errors

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#328]
Hi,

I am trying to upgrade our Origen version to 0.42.0 and I am now getting an error for previously working parameter sets.  Here is an example:

~~~ruby
[1] pry(#<Our::Interface>)> test_instance.alarms.class
=> Origen::Parameters::Set
[2] pry(#<Our::Interface>)> test_instance.alarms
=> {:on_fail=>true, :on_pass=>false}
[3] pry(#<Our::Interface>)> test_instance.alarms.on_fail
=> true
[4] pry(#<Our::Interface>)> test_instance.alarms.on_pass
NoMethodError: undefined method `on_pass' for {:on_fail=>true, :on_pass=>false}:Origen::Parameters::Set
from /users/user/origen/.origen/gems/ruby/2.3.0/bundler/gems/origen-da802b93dda1/lib/origen/parameters/set.rb:65:in `method_missing'
~~~

It seems that parameter sets now don't support false values.

thx

**Comment by rlaj** [comment]
@info-rchitect , do you know what Origen version you were running previously?  I can confirm the same issue in 0.36.1.

**Comment by info-rchitect** [comment]
0.34.2

**Comment by info-rchitect** [comment]
@rlaj I think I found a simple fix but having issues running spec tests, stay tuned.

**Comment by info-rchitect** [comment]
Here is my fix:

![image](https://user-images.githubusercontent.com/26782653/52009960-d560d500-2499-11e9-864e-f15a80246d0c.png)

[Line 64](https://github.com/Origen-SDK/origen/blob/master/lib/origen/parameters/set.rb#L64) is the culprit.

**Comment by rlaj** [comment]
Ok, looks right.  So does that mean it was never really working properly and there was some subtle change to Ruby Hash method_missing that now throws an error?

**Comment by info-rchitect** [comment]
@rlaj Yeah i cannot figure it out as the set.rb file looks unchanged.

**Comment by ginty** [comment]
No idea what the root cause is here either, but wondering if that really is the fix - i.e. will someone try to assign a parameter value of nil at some point?

This might be better (untested):

~~~ruby
if !has_key?(method)
  super
else
  val = self[method]
  if val.is_a?(Set)
    # ...
~~~

**Comment by info-rchitect** [comment]
@ginty @rlaj I made a [slight change to the fix](https://github.com/Origen-SDK/origen/pull/327/commits/379dca62bd77198a6fc2b4c5667572465fac75dc).  Let me know if we are ready to merge.

**Comment by info-rchitect** [comment]
fixed [here](https://github.com/Origen-SDK/origen/pull/327)
