### ISSUE TITLE
RSPEC syntax

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#345]
Hi,

I am writing a bunch of unit tests from scratch and found [this article](http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/) that made me wonder if our prevailing usage model (should) might need to be examined, given the fact that delegation patterns are likely used quite a bit in origen.  I am not proposing re-writing our spec tests, really just wanted to start a discussion to help me as I write my new unit tests.

thx

**Comment by ginty** [comment]
Probably we should start to use the expect syntax, I've noticed @coreyeng has been doing it in new work, though I must admit I have not.

**Comment by info-rchitect** [comment]
https://github.com/Origen-SDK/origen/blob/master/spec/spec_helper.rb#L72

'expect' syntax is enabled
