### ISSUE TITLE
parameter set API does not check for existing methods well enough

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#352]
Reproduce:

1. select Ruby 2.6
2. use branch `param_set_bug_ruby_2p6`
3.  `bundle exec rspec spec/parameters_spec.rb`

This is due to the new enumerator method [chain](https://ruby-doc.org/core-2.6.3/Enumerable.html#method-i-chain). 

In reality, this is not an issue particular to the `chain` method, rather the parameter set API does not check if the set key values are available methods.  

The failing code line is [here](https://github.com/Origen-SDK/origen/blob/master/lib/origen/parameters/set.rb#L22).

I will try debugging it and make a PR but if the owners of this code could take a look it might go faster.

thx

**Comment by ginty** [comment]
Sounds like the same as #303
