### ISSUE TITLE
Componentable seems to have changed behavior

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#386]
Hi,

I am using Componentable, specifically the `add` method.  I am getting the following error:

~~~shell
COMPLETE CALL STACK
-------------------
undefined method `key?' for nil:NilClass
/users/user/origen_gems/peologin_v5p7_gems/.origen/gems/ruby/2.6.0/gems/origen-0.55.3/lib/origen/componentable.rb:451:in `_instantiate_class'
~~~

The NilClass object is `@_componentable_container`, when does this get initialized?

**Comment by coreyeng** [comment]
It gets set [here](https://github.com/Origen-SDK/origen/blob/master/lib/origen/componentable.rb#L40-L55), which is tied to [the model init](https://github.com/Origen-SDK/origen/blob/master/lib/origen/componentable.rb#L36-L38), which ultimately gets called from the [model initializer](https://github.com/Origen-SDK/origen/blob/master/lib/origen/componentable.rb#L36-L38)

**Comment by info-rchitect** [comment]
@coreyeng What does the user have to do to get it initialized?  Should the user be able to add components directly using the `add` method alone or is there some other step needed?

**Comment by coreyeng** [comment]
It should be automatic if the including class inherits from `Origen::Model`. If not, then you'll have to boot it manually, but I've got some [docs on the web for that](https://origen-sdk.org/origen/guides/models/componentable/#Booting_the_Includer). There some [namespacing constraints](https://origen-sdk.org/origen/guides/models/componentable/#Includer_Class_Organization) that must be met as well.

I'm assuming too that it works in the general sense? You can boot up your application, correct? Its not something induced in an Origen update (though the specs should've failed) or by running Ruby 2.6? All models have empty `components` by default, so just `dut.components` should return an empty hash (with indifference access).

**Comment by info-rchitect** [comment]
> It should be automatic if the including class inherits from Origen::Model. If not, then you'll have to boot it manually, but I've got some docs on the web for that. There some namespacing constraints that must be met as well.
> I'm assuming too that it works in the general sense? You can boot up your application, correct? Its not something induced in an Origen update (though the specs should've failed) or by running Ruby 2.6? All models have empty components by default, so just dut.components should return an empty hash (with indifference access).

Thanks @coreyeng that worked
