### ISSUE TITLE
"origen rc init" bug with git

### ISSUE THREAD

**Issue by redxeth** [Origen-SDK/origen#51]
"git remote --verbose" command fails as part of running 'origen rc init' after making a new app before first checkin (origen new workspace).

init rc command needs to be updated to do: 
-	git init
-	git add --all 
-	git commit –m “Initial Commit”
-	git remote add origin ssh://git@sw-stash.freescale.net/nvm/blah.git
-	git push origin master

Asssuming that .gitignore is correct

**Comment by ginty** [comment]
Fixed in 0.7.12
