### ISSUE TITLE
Force overwrite of the system gem if it already exists

### ISSUE THREAD

**Issue by priyavadan** [Origen-SDK/origen#53]
FileUtils.cp currently does not overwrite an existing gem but throws an exception. Either force overwrite or handle the exception and continue.

**Comment by ginty** [comment]
Not sure that it should force an overwrite here, I think it should just do nothing if the user's gem directory already has it.

**Comment by priyavadan** [comment]
@ginty yup, my bad, it should look if file exists and skip. PR #54 has the updates.

**Comment by priyavadan** [comment]
Fixed in v0.7.13
