### ISSUE TITLE
0.12.0 interactive throws error

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#85]
Hi,

I forked a branch and went to start developing.  Bundler did its thing OK and I typed 'origen i' and got the following:

![image](https://cloud.githubusercontent.com/assets/26782653/26762064/f862f40a-4900-11e7-8c09-669d87ab8d12.png)

Here is what is in the default.rb target fil:

```ruby
debug.rb
```

Here is what is in debug.rb:

```ruby
load "#{Origen.root}/target/production.rb"

Origen.mode = :debug
```

And here is what is in production.rb:

```ruby
$top = C99::SOC.new
$nvm = C99::NVM.new
$tester = OrigenTesters::J750.new

$dut = $top
$soc = $top

Origen.mode = :production
```

I changed the default.rb target to the following and the error went away:

```ruby
load "#{Origen.root}/target/debug.rb"
```

Did something change recently, I though Origen always allowed referencing other target files.  Ot is this a hole in the spec testing for interactive mode?

**Comment by ginty** [comment]
On Linux, target/default.rb is a symlink to target/debug.rb

I guess this is maybe a Git thing where it just creates the symlink as a file containing the path to what it should point to.

If you want to create a PR to change target/default.rb from a symlink to a file containing the same content as target/debug.rb then go ahead.

Thanks!
