### ISSUE TITLE
Web compile not behaving as expected with gem

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#90]
Hi,

When I run the web compile command it seems like Origen is executing the last target I had run.  Any ideas?  I am using a custom 'ask' command.

thx,
bac

C:\origen\nemawashi>origen ask -t engdwlot
[INFO]       0.016[0.016]    || Nemawashi: Parsing AMG 
...
[INFO]       7.040[0.016]    || Target 'engdwlot' completed

C:\origen\nemawashi>origen web compile -r
[INFO]       0.016[0.000]    || Nemawashi: Parsing AMG ''
...

**Comment by ginty** [comment]
Not sure what you mean here, running origen web compile will load the current workspace's currently set target unless you specify an alternative via the -t option.

Can you elaborate more?

**Comment by info-rchitect** [comment]
I wasn't expecting web compile to do anything but compile the webpage.

**Comment by ginty** [comment]
OK, it does do that within the context of the current target though, so it does load it

**Comment by info-rchitect** [comment]
why is the target relevant?

**Comment by ginty** [comment]
Some apps may want to build their web docs per target, for some (many?) these days it is probably not relevant.
It has always done this though and we can't change it without breaking legacy apps so its not going away.

On the flip side, why does it matter if it loads the target?

**Comment by coreyeng** [comment]
Hello. (Inviting myself into the conversion) I think its just unexpected. When I first started working with the documentation generators, I too was surprised that I couldn't compile the web docs when I had an error (I think it was require file was wrong) in my controller.  I don't think there's anything wrong with it, its just unexpected and for most applications it is unrelated.

That said though, I do use the target in some my test blocks where I threw in the 'descriptions' into my 'parameters list' and auto-generate the web page from that during web compile time. This keeps them in sync. It can help serve as a 'document from source' mechanism. Though, if you're not using something like that, it does seem irrelevant.

**Comment by info-rchitect** [comment]
thx folks I get it
