### ISSUE TITLE
Target name matching

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#91]
HI,

Why is this command failing?  I have 2 targets named similarly and expected them both to run.

thx

~~~shell
C:\origen\nemawashi>origen i -t engdwlite

Install the reportbuilder gem version ~>1.4 for using reportbuilder functions.

Install the spreadsheet gem version ~>1.1.1 for using spreadsheet functions.
Please try again with one of the following targets:
engdwlite.rb
engdwlite_rv_mbist.rb
~~~

**Comment by ginty** [comment]
It doesn't work like that, you can only have one target live at a time.

The target is supposed to specify what the universally agreed variable 'dut' refers to, it doesn't really make sense to run origen i with multiple targets at the same time since there can only ever be one DUT.

**Comment by info-rchitect** [comment]
OK so I may be abusing targets.  In my main app I have one model loaded but in my analytics gem I am using targets as queries to a database.  How would you handle it?

~~~rurby
query :my_db, :my_query do
  amg :my_amg do
    filter_by_prod 'myprod'
    filter_by_lot 'mylot'
    filter_by_oper 'myoper'
    filter_by_test /^mbist/
  end
end.run
~~~

**Comment by ginty** [comment]
Depends if each query represents a specific device, or if your different queries are all for the same device.

If each query is a device, then you should have a target for each like you have, but you should probably have multiple models (which may all inherit from the same base model which contains the bulk of the logic).

Essentially your targets should always be little more than this:

~~~ruby
MyApp::Device1.new
~~~

Then any data related to defining the query for that device should be in the model.

If you do only have one device, then you should only have one model, but only 1 target too.

If you are looking for a mechanism to pass query information from the command line then you should probably add an app-specific command for that, or else augment the existing commands with some app-specific command options.

**Comment by info-rchitect** [comment]
thx
