### ISSUE TITLE
Pin model schema

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#96]
Hi,

Given the rich pin model of Origen I was wondering if it made sense to create a formal schema.  I think most Origen users would agree that there is no IP-XACT version of pins except IEEE1687 \*shudder\*.  Many users are probably sick and tired of parsing convoluted Excel files with broken macros to find the necessary pin functionality across device mode and package types.  

If someone with a pretty complex device, meaning it uses all or most of the pin model, could export some pins I would gladly write the schema and add it to cross-origen as an import.  I think just using JSON to export an instantiated device pins would work.  Any takers?

**Comment by ginty** [comment]
@welguisz, any thoughts on this one?

**Comment by ginty** [comment]
@aaronburg, of interest to you?

**Comment by welguisz** [comment]
I have too many thoughts.  Think it would be better to discuss in person to figure this out much better than discuss in a thread.

**Comment by chrisnappi** [comment]
I'd like to bring in Kristen Mason or Oleg (Spider guy) for this discussion.  I think it is a good idea to try to push for some standard description.

**Comment by info-rchitect** [comment]
@welguisz I would be glad to meet you in Scotland for a pint if that will get this discussion moving.
